INSERT INTO USER (IDUSER, USERNAME, PASSWORD, ACCOUNTTYPE) VALUES (SEQ_USER.NEXTVAL, 'admin', '1234', 1);
INSERT INTO PARTICIPANT (IDPARTICIPANT, NAME, AGE, STATE, ACTIVE) VALUES (SEQ_PARTICIPANT.NEXTVAL, 'Participante 1', 32, 'BA', true);
INSERT INTO PARTICIPANT (IDPARTICIPANT, NAME, AGE, STATE, ACTIVE) VALUES (SEQ_PARTICIPANT.NEXTVAL, 'Participante 2', 38, 'SP', true);
INSERT INTO VOTING (IDVOTING, DATECREATION, DATESTART, DATEEND, ACTIVE) VALUES (SEQ_VOTING.NEXTVAL, PARSEDATETIME('01-12-2020', 'dd-MM-yyyy'), 
PARSEDATETIME('16-12-2020', 'dd-MM-yyyy'), PARSEDATETIME('31-12-2020', 'dd-MM-yyyy'), true);
INSERT INTO VOTINGPARTICIPANTS (IDVOTINGPARTICIPANTS, IDVOTING, IDPARTICIPANT, VOTES) VALUES (SEQ_IDVOTINGPARTICIPANTS.NEXTVAL, 1, 1, 0);
INSERT INTO VOTINGPARTICIPANTS (IDVOTINGPARTICIPANTS, IDVOTING, IDPARTICIPANT, VOTES) VALUES (SEQ_IDVOTINGPARTICIPANTS.NEXTVAL, 1, 2, 0);